"""New migration apperantly something wnet wrong

Revision ID: 24f3d13aa4df
Revises: a7227a99a51f
Create Date: 2023-08-27 17:07:44.211308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24f3d13aa4df"
down_revision: Union[str, None] = "a7227a99a51f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bills", sa.Column("bill_name", sa.String(), nullable=True))
    op.add_column("bills", sa.Column("bill_category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "bill_category")
    op.drop_column("bills", "bill_name")
    # ### end Alembic commands ###
