"""Initial migration

Revision ID: a7227a99a51f
Revises: 
Create Date: 2023-08-27 15:15:06.037323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7227a99a51f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_patrick", sa.Boolean(), nullable=True),
        sa.Column("balance", sa.Integer(), nullable=True),
        sa.Column("male", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_bill_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_bill_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bills")
    op.drop_table("users")
    # ### end Alembic commands ###
